### ISSUE TITLE
Adding a PIC clarifications

### ISSUE THREAD

**Issue by Twinniss** [BirchJD/RPiPIC#1]
Trying to understand how to add a PIC to the devices list:

What I am not getting is the Obj Address; how is that identified through documentation?

Mostly for other readers:
I noticed this part in PIC_DEVICES:
#/*    PIC Device Name,                                                     */
#/*    [                                                                    */
#/*       Memory Type, PIC Memory Area, Start Address, Length, Obj Address, */
#/*       Store/Restore Mask,                                               */
#/*       ...                                                               */
#/*    ],                                                                   */

Where I think Memory Type and PIC Memory Area should be grouped together to avoid confusion. 
Something like maybe: (Memory Type, PIC Memory Area), Start Address, ...

Took a bit to figure out. 
Also like to clear up that Start Address for writes is based off of what the Load Configuration command sets the PC to

Working with a 16F18346 btw
Load Config sets PC to 0x8000

**Comment by BirchJD** [comment]
16F18346 support has now been added. It may be a bit late to be of use to you now.
I found with later models of PIC, there can be process differences as well as memory map differences.
A basic example project has also been added.
These look really neat devices, I may make use of them myself in future.
